apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: deploylens
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/puliththewmika/deploylens-frontend:dcd98a9
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: SERVICE_NAME
              value: frontend
            - name: ERROR_RATE
              value: "0"
            - name: LATENCY_MS
              value: "0"
            - name: ORDERS_URL
              value: http://orders:8000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
