apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: deploylens
  labels:
    app: orders
spec:
  selector:
    app: orders
  ports:
    - name: http
      port: 8000
      targetPort: http
