apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payments
  namespace: deploylens
  labels:
    app: payments
spec:
  selector:
    matchLabels:
      app: payments
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
