apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploylens-agent.fullname" (dict "root" . "component" "webhook-tokens") }}
  labels:
    {{- include "deploylens-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-webhook-token: {{ .Values.webhookTokens.github | quote }}
  argocd-webhook-token: {{ .Values.webhookTokens.argocd | quote }}
  alertmanager-webhook-token: {{ .Values.webhookTokens.alertmanager | quote }}
