apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PulithThewmika/deploylens.git
    targetRevision: dev
    path: sample-app/deploy
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: deploylens
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
