"""Cluster-agent configuration (EPIC-022 / E22-T3).

Every value comes from the install manifest generated by E22-T2
(services/ingest/app/routers/install.py) — CLUSTER_TOKEN and
DEPLOYLENS_ENDPOINT are the two required env vars; everything else has a
sane default so the agent still runs against a hand-edited manifest.
"""

from __future__ import annotations

import os
from urllib.parse import urlparse

CLUSTER_TOKEN = os.environ.get("CLUSTER_TOKEN", "")
DEPLOYLENS_ENDPOINT = os.environ.get("DEPLOYLENS_ENDPOINT", "")

# The bearer token is sent on every request to DEPLOYLENS_ENDPOINT — over
# plain HTTP it's exposed to anyone on-path. Local/CI runs (e.g. against
# host.docker.internal) need the escape hatch; a real install manifest
# always sets INGEST_PUBLIC_URL to an https address (security review, E22-T3).
ALLOW_INSECURE_ENDPOINT = os.environ.get("ALLOW_INSECURE_ENDPOINT", "").lower() in ("1", "true")

HEARTBEAT_INTERVAL_SECONDS = int(os.environ.get("HEARTBEAT_INTERVAL_SECONDS", "60"))
QUERY_POLL_INTERVAL_SECONDS = int(os.environ.get("QUERY_POLL_INTERVAL_SECONDS", "10"))
ARGOCD_RECHECK_INTERVAL_SECONDS = int(os.environ.get("ARGOCD_RECHECK_INTERVAL_SECONDS", "300"))

BACKOFF_INITIAL_SECONDS = float(os.environ.get("BACKOFF_INITIAL_SECONDS", "1"))
BACKOFF_MAX_SECONDS = float(os.environ.get("BACKOFF_MAX_SECONDS", "60"))

AGENT_VERSION = os.environ.get("AGENT_VERSION", "0.1.0")


def validate() -> None:
    missing = [name for name, value in (("CLUSTER_TOKEN", CLUSTER_TOKEN), ("DEPLOYLENS_ENDPOINT", DEPLOYLENS_ENDPOINT)) if not value]
    if missing:
        raise RuntimeError(
            f"Required env var(s) not set: {', '.join(missing)}. "
            "These come from the install manifest generated by GET /install/:token.yaml."
        )
    if urlparse(DEPLOYLENS_ENDPOINT).scheme != "https" and not ALLOW_INSECURE_ENDPOINT:
        raise RuntimeError(
            f"DEPLOYLENS_ENDPOINT ({DEPLOYLENS_ENDPOINT!r}) must be https:// — the cluster bearer token is "
            "sent on every request. Set ALLOW_INSECURE_ENDPOINT=true only for local/dev testing."
        )
    # Bug found in review, E22-T3: nothing previously rejected a
    # non-positive interval (e.g. QUERY_POLL_INTERVAL_SECONDS=0 would spin
    # the query loop with no delay at all) or a BACKOFF_INITIAL_SECONDS
    # greater than BACKOFF_MAX_SECONDS (the first retry would then exceed
    # the configured cap).
    for name, value in (
        ("HEARTBEAT_INTERVAL_SECONDS", HEARTBEAT_INTERVAL_SECONDS),
        ("QUERY_POLL_INTERVAL_SECONDS", QUERY_POLL_INTERVAL_SECONDS),
        ("ARGOCD_RECHECK_INTERVAL_SECONDS", ARGOCD_RECHECK_INTERVAL_SECONDS),
        ("BACKOFF_INITIAL_SECONDS", BACKOFF_INITIAL_SECONDS),
        ("BACKOFF_MAX_SECONDS", BACKOFF_MAX_SECONDS),
    ):
        if value <= 0:
            raise RuntimeError(f"{name} must be positive, got {value!r}")
    if BACKOFF_INITIAL_SECONDS > BACKOFF_MAX_SECONDS:
        raise RuntimeError(
            f"BACKOFF_INITIAL_SECONDS ({BACKOFF_INITIAL_SECONDS}) must not exceed "
            f"BACKOFF_MAX_SECONDS ({BACKOFF_MAX_SECONDS})"
        )
