"""Cluster-agent configuration (EPIC-022 / E22-T3).

Every value comes from the install manifest generated by E22-T2
(services/ingest/app/routers/install.py) — CLUSTER_TOKEN and
DEPLOYLENS_ENDPOINT are the two required env vars; everything else has a
sane default so the agent still runs against a hand-edited manifest.
"""

from __future__ import annotations

import os

CLUSTER_TOKEN = os.environ.get("CLUSTER_TOKEN", "")
DEPLOYLENS_ENDPOINT = os.environ.get("DEPLOYLENS_ENDPOINT", "")

HEARTBEAT_INTERVAL_SECONDS = int(os.environ.get("HEARTBEAT_INTERVAL_SECONDS", "60"))
QUERY_POLL_INTERVAL_SECONDS = int(os.environ.get("QUERY_POLL_INTERVAL_SECONDS", "10"))
ARGOCD_RECHECK_INTERVAL_SECONDS = int(os.environ.get("ARGOCD_RECHECK_INTERVAL_SECONDS", "300"))

BACKOFF_INITIAL_SECONDS = float(os.environ.get("BACKOFF_INITIAL_SECONDS", "1"))
BACKOFF_MAX_SECONDS = float(os.environ.get("BACKOFF_MAX_SECONDS", "60"))

AGENT_VERSION = os.environ.get("AGENT_VERSION", "0.1.0")


def validate() -> None:
    missing = [name for name, value in (("CLUSTER_TOKEN", CLUSTER_TOKEN), ("DEPLOYLENS_ENDPOINT", DEPLOYLENS_ENDPOINT)) if not value]
    if missing:
        raise RuntimeError(
            f"Required env var(s) not set: {', '.join(missing)}. "
            "These come from the install manifest generated by GET /install/:token.yaml."
        )
